#!/bin/bash

#VERSION=1
if [[ ! -d /root/dotfiles ]]; then
  cd /root
  git clone https://github.com/jgallen23/dotfiles.git
  . dotfiles/bin/dotfiles

  if [[ -f /root/.bashrc ]]; then
    echo "source /root/.bash_profile" >> /root/.bashrc
  fi

  bash dotfiles/vim-install.sh

  ssh-keygen -f /root/.ssh/id_rsa -t rsa -N ''

  echo "Add this to github"
  cat /root/.ssh/id_rsa.pub
fi
