#!/bin/bash

#install aufs
apt-get update && apt-get install -y git htop linux-image-extra-$(uname -r)

#update ssh port to 2201
sed -i 's/Port 22/Port 2201/' /etc/ssh/sshd_config
service ssh restart

#install docker
curl -sSL https://get.docker.io/ubuntu/ | sudo sh

#load my fork of envy
mkdir /code
cd /code
git clone https://github.com/jgallen23/envy.git
cd envy
docker build -t jgallen23/envy .

#start envy
docker run -d --name envy --net host -v /mnt/data:/data -v /var/run/docker.sock:/var/run/docker.sock -e HOST_DATA=/mnt/data jgallen23/envy

#set timezone
sudo timedatectl set-timezone America/Los_Angeles
